//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Kursach.DB.DBKursach
{

    [Persistent(@"device.Machine")]
    public partial class device_Machine : XPLiteObject
    {
        Guid fGUID;
        [Key(true)]
        public Guid GUID
        {
            get { return fGUID; }
            set { SetPropertyValue<Guid>(nameof(GUID), ref fGUID, value); }
        }
        string fName;
        [Size(128)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        device_Type fTypeGUID;
        [Association(@"device_MachineReferencesdevice_Type")]
        public device_Type TypeGUID
        {
            get { return fTypeGUID; }
            set { SetPropertyValue<device_Type>(nameof(TypeGUID), ref fTypeGUID, value); }
        }
        device_Operations fOperationsGUID;
        [Association(@"device_MachineReferencesdevice_Operations")]
        public device_Operations OperationsGUID
        {
            get { return fOperationsGUID; }
            set { SetPropertyValue<device_Operations>(nameof(OperationsGUID), ref fOperationsGUID, value); }
        }
        DateTime fCommissioningDate;
        public DateTime CommissioningDate
        {
            get { return fCommissioningDate; }
            set { SetPropertyValue<DateTime>(nameof(CommissioningDate), ref fCommissioningDate, value); }
        }
        DateTime fDateOfChange;
        public DateTime DateOfChange
        {
            get { return fDateOfChange; }
            set { SetPropertyValue<DateTime>(nameof(DateOfChange), ref fDateOfChange, value); }
        }
        DateTime fDeletedDate;
        public DateTime DeletedDate
        {
            get { return fDeletedDate; }
            set { SetPropertyValue<DateTime>(nameof(DeletedDate), ref fDeletedDate, value); }
        }
        [Association(@"device_RepairScheduleReferencesdevice_Machine")]
        public XPCollection<device_RepairSchedule> device_RepairSchedules { get { return GetCollection<device_RepairSchedule>(nameof(device_RepairSchedules)); } }
    }

}
