//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Kursach.DB.DBKursach
{

    [Persistent(@"device.Staff")]
    public partial class device_Staff : XPLiteObject
    {
        Guid fGUID;
        [Key(true)]
        public Guid GUID
        {
            get { return fGUID; }
            set { SetPropertyValue<Guid>(nameof(GUID), ref fGUID, value); }
        }
        string fFirstName;
        [Size(20)]
        public string FirstName
        {
            get { return fFirstName; }
            set { SetPropertyValue<string>(nameof(FirstName), ref fFirstName, value); }
        }
        string fMiddleName;
        [Size(20)]
        public string MiddleName
        {
            get { return fMiddleName; }
            set { SetPropertyValue<string>(nameof(MiddleName), ref fMiddleName, value); }
        }
        string fLastName;
        [Size(20)]
        public string LastName
        {
            get { return fLastName; }
            set { SetPropertyValue<string>(nameof(LastName), ref fLastName, value); }
        }
        DateTime fDateOfBirth;
        public DateTime DateOfBirth
        {
            get { return fDateOfBirth; }
            set { SetPropertyValue<DateTime>(nameof(DateOfBirth), ref fDateOfBirth, value); }
        }
        decimal fPhoneNumber;
        public decimal PhoneNumber
        {
            get { return fPhoneNumber; }
            set { SetPropertyValue<decimal>(nameof(PhoneNumber), ref fPhoneNumber, value); }
        }
        string fAddress;
        public string Address
        {
            get { return fAddress; }
            set { SetPropertyValue<string>(nameof(Address), ref fAddress, value); }
        }
        device_Position fPositionGUID;
        [Association(@"device_StaffReferencesdevice_Position")]
        public device_Position PositionGUID
        {
            get { return fPositionGUID; }
            set { SetPropertyValue<device_Position>(nameof(PositionGUID), ref fPositionGUID, value); }
        }
        DateTime fDateArrivalWork;
        public DateTime DateArrivalWork
        {
            get { return fDateArrivalWork; }
            set { SetPropertyValue<DateTime>(nameof(DateArrivalWork), ref fDateArrivalWork, value); }
        }
        DateTime fDateOfChange;
        public DateTime DateOfChange
        {
            get { return fDateOfChange; }
            set { SetPropertyValue<DateTime>(nameof(DateOfChange), ref fDateOfChange, value); }
        }
        DateTime fDeletedDate;
        public DateTime DeletedDate
        {
            get { return fDeletedDate; }
            set { SetPropertyValue<DateTime>(nameof(DeletedDate), ref fDeletedDate, value); }
        }
        [Association(@"device_WorkTeamReferencesdevice_Staff")]
        public XPCollection<device_WorkTeam> device_WorkTeams { get { return GetCollection<device_WorkTeam>(nameof(device_WorkTeams)); } }
    }

}
