//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Kursach.DB.DBKursach
{

    [NonPersistent]
    public partial class MachineView : XPLiteObject
    {
        Guid fGUID;
        public Guid GUID
        {
            get { return fGUID; }
            set { SetPropertyValue<Guid>(nameof(GUID), ref fGUID, value); }
        }
        string fName;
        [Size(128)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fTypeGUID;
        [Size(128)]
        public string TypeGUID
        {
            get { return fTypeGUID; }
            set { SetPropertyValue<string>(nameof(TypeGUID), ref fTypeGUID, value); }
        }
        string fOperationsGUID;
        [Size(128)]
        public string OperationsGUID
        {
            get { return fOperationsGUID; }
            set { SetPropertyValue<string>(nameof(OperationsGUID), ref fOperationsGUID, value); }
        }
        DateTime fCommissioningDate;
        public DateTime CommissioningDate
        {
            get { return fCommissioningDate; }
            set { SetPropertyValue<DateTime>(nameof(CommissioningDate), ref fCommissioningDate, value); }
        }
        DateTime fDateOfChange;
        public DateTime DateOfChange
        {
            get { return fDateOfChange; }
            set { SetPropertyValue<DateTime>(nameof(DateOfChange), ref fDateOfChange, value); }
        }
        DateTime fDeletedDate;
        public DateTime DeletedDate
        {
            get { return fDeletedDate; }
            set { SetPropertyValue<DateTime>(nameof(DeletedDate), ref fDeletedDate, value); }
        }
    }

}
