//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Kursach.DB.DBKursach
{

    [NonPersistent]
    public partial class OperationsView : XPLiteObject
    {
        Guid fGUID;
        public Guid GUID
        {
            get { return fGUID; }
            set { SetPropertyValue<Guid>(nameof(GUID), ref fGUID, value); }
        }
        string fNameOperations;
        [Size(128)]
        public string NameOperations
        {
            get { return fNameOperations; }
            set { SetPropertyValue<string>(nameof(NameOperations), ref fNameOperations, value); }
        }
        string fTypeOperationsGUID;
        [Size(128)]
        public string TypeOperationsGUID
        {
            get { return fTypeOperationsGUID; }
            set { SetPropertyValue<string>(nameof(TypeOperationsGUID), ref fTypeOperationsGUID, value); }
        }
        DateTime fOperationTime;
        public DateTime OperationTime
        {
            get { return fOperationTime; }
            set { SetPropertyValue<DateTime>(nameof(OperationTime), ref fOperationTime, value); }
        }
        Guid fWorkTeamGUID;
        public Guid WorkTeamGUID
        {
            get { return fWorkTeamGUID; }
            set { SetPropertyValue<Guid>(nameof(WorkTeamGUID), ref fWorkTeamGUID, value); }
        }
        DateTime fDateOfChange;
        public DateTime DateOfChange
        {
            get { return fDateOfChange; }
            set { SetPropertyValue<DateTime>(nameof(DateOfChange), ref fDateOfChange, value); }
        }
        DateTime fDeletedDate;
        public DateTime DeletedDate
        {
            get { return fDeletedDate; }
            set { SetPropertyValue<DateTime>(nameof(DeletedDate), ref fDeletedDate, value); }
        }
    }

}
