//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Kursach.DBKursach
{

    [Persistent(@"device.WorkTeam")]
    public partial class device_WorkTeam : XPLiteObject
    {
        Guid fGUID;
        [Key(true)]
        public Guid GUID
        {
            get { return fGUID; }
            set { SetPropertyValue<Guid>(nameof(GUID), ref fGUID, value); }
        }
        decimal fNumberOfWorkers;
        public decimal NumberOfWorkers
        {
            get { return fNumberOfWorkers; }
            set { SetPropertyValue<decimal>(nameof(NumberOfWorkers), ref fNumberOfWorkers, value); }
        }
        device_TypeWorkTeam fTypeWorkTeamGUID;
        [Association(@"device_WorkTeamReferencesdevice_TypeWorkTeam")]
        public device_TypeWorkTeam TypeWorkTeamGUID
        {
            get { return fTypeWorkTeamGUID; }
            set { SetPropertyValue<device_TypeWorkTeam>(nameof(TypeWorkTeamGUID), ref fTypeWorkTeamGUID, value); }
        }
        device_ProfileWorkTeam fProfileWorkTeamGUID;
        [Association(@"device_WorkTeamReferencesdevice_ProfileWorkTeam")]
        public device_ProfileWorkTeam ProfileWorkTeamGUID
        {
            get { return fProfileWorkTeamGUID; }
            set { SetPropertyValue<device_ProfileWorkTeam>(nameof(ProfileWorkTeamGUID), ref fProfileWorkTeamGUID, value); }
        }
        device_WorkShifts fWorkShiftsGUID;
        [Association(@"device_WorkTeamReferencesdevice_WorkShifts")]
        public device_WorkShifts WorkShiftsGUID
        {
            get { return fWorkShiftsGUID; }
            set { SetPropertyValue<device_WorkShifts>(nameof(WorkShiftsGUID), ref fWorkShiftsGUID, value); }
        }
        device_Staff fStaffGUID;
        [Association(@"device_WorkTeamReferencesdevice_Staff")]
        public device_Staff StaffGUID
        {
            get { return fStaffGUID; }
            set { SetPropertyValue<device_Staff>(nameof(StaffGUID), ref fStaffGUID, value); }
        }
        [Association(@"device_OperationsReferencesdevice_WorkTeam")]
        public XPCollection<device_Operations> device_Operationss { get { return GetCollection<device_Operations>(nameof(device_Operationss)); } }
    }

}
