//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Kursach.DBKursach
{

    [Persistent(@"device.Operations")]
    public partial class device_Operations : XPLiteObject
    {
        Guid fGUID;
        [Key(true)]
        public Guid GUID
        {
            get { return fGUID; }
            set { SetPropertyValue<Guid>(nameof(GUID), ref fGUID, value); }
        }
        string fNameOperations;
        [Size(128)]
        public string NameOperations
        {
            get { return fNameOperations; }
            set { SetPropertyValue<string>(nameof(NameOperations), ref fNameOperations, value); }
        }
        device_TypeOperations fTypeOperationsGUID;
        [Association(@"device_OperationsReferencesdevice_TypeOperations")]
        public device_TypeOperations TypeOperationsGUID
        {
            get { return fTypeOperationsGUID; }
            set { SetPropertyValue<device_TypeOperations>(nameof(TypeOperationsGUID), ref fTypeOperationsGUID, value); }
        }
        DateTime fOperationTime;
        public DateTime OperationTime
        {
            get { return fOperationTime; }
            set { SetPropertyValue<DateTime>(nameof(OperationTime), ref fOperationTime, value); }
        }
        DateTime fDateOfChange;
        public DateTime DateOfChange
        {
            get { return fDateOfChange; }
            set { SetPropertyValue<DateTime>(nameof(DateOfChange), ref fDateOfChange, value); }
        }
        DateTime fDeletedDate;
        public DateTime DeletedDate
        {
            get { return fDeletedDate; }
            set { SetPropertyValue<DateTime>(nameof(DeletedDate), ref fDeletedDate, value); }
        }
        device_WorkTeam fWorkTeamGUID;
        [Association(@"device_OperationsReferencesdevice_WorkTeam")]
        public device_WorkTeam WorkTeamGUID
        {
            get { return fWorkTeamGUID; }
            set { SetPropertyValue<device_WorkTeam>(nameof(WorkTeamGUID), ref fWorkTeamGUID, value); }
        }
        [Association(@"device_MachineReferencesdevice_Operations")]
        public XPCollection<device_Machine> device_Machines { get { return GetCollection<device_Machine>(nameof(device_Machines)); } }
        [Association(@"device_ProductionReferencesdevice_Operations")]
        public XPCollection<device_Production> device_Productions { get { return GetCollection<device_Production>(nameof(device_Productions)); } }
    }

}
